;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        beginning-of-visual-line
        c-electric-colon
        easy-kill
        electric-newline-and-maybe-indent
        end-of-buffer
        end-of-visual-line
        helm-M-x
        helm-find-files
        helm-mini
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        my-fancy-newline
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-meta-return
        org-return-indent
        org-self-insert-command
        org-yank
        prelude-move-beginning-of-line
        sp-kill-hybrid-sexp
        split-line
        tab-to-tab-stop
        typescript-insert-and-indent
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ))
