(prelude-require-package 'color-theme)
(prelude-require-package 'minimap)
(prelude-require-package 'multiple-cursors)
(prelude-require-package 'ack)
(prelude-require-package 'ag)
(prelude-require-package 'editorconfig)
(prelude-require-package 'stylus-mode)
(prelude-require-package 'origami)
(prelude-require-package 'yasnippet)
(prelude-require-package 'js-doc)
(prelude-require-package 'js2-refactor)
(prelude-require-package 'smart-forward)
(prelude-require-package 'twittering-mode)

(require 'ob-js)
(require 'ob-css)
